services:
  - type: web
    name: autopotion-license-api
    runtime: python
    repo: https://github.com/wandersonlt/AutoPotion---POE2---PG
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: autopotion-db
          property: connectionString
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: autopotion-db
    databaseName: autopotion_licenses
    user: autopotion_user
    plan: free
